### ISSUE TITLE
Day 2 and Day 3 links not working

### ISSUE THREAD

**Issue by steveermish** [LadyNaggaga/ASP.NETCoreMVA#10]
Hi, it appears all of the links under day 2 and day 3 are no longer working and should be updated to reflect the new _old folder structure.

Example:
https://github.com/LadyNaggaga/ASP.NETCoreMVA/blob/master/Advanced/Entityframeworkcore.md

Should point to:
https://github.com/LadyNaggaga/ASP.NETCoreMVA/blob/master/Advanced_old/Entityframeworkcore.md

**Comment by LadyNaggaga** [comment]
@steveermish Thank you   We are rewriting the MVAs to reflect the new MSBuild toolset.  All the links will be working by Friday.
