### ISSUE TITLE
MVA courses

### ISSUE THREAD

**Issue by TechWatching** [LadyNaggaga/ASP.NETCoreMVA#3]
Nice repo ! Are the 'Day 2 Intermediate Guide to ASP.NET Core 1.0' and 'Day 3 .NET Core on Linux / Cross Platform' be available on MVA  ?

**Comment by LadyNaggaga** [comment]
@TechWatching  Yes they both should be out soon.  Day 2 should be out the 1st or 2nd week of  November :)

**Comment by rs38** [comment]
waiting too 👍

**Comment by TechWatching** [comment]
@LadyNaggaga Could you post the link to the course when it will be available ? I still have not seen Day 2 on MVA.

**Comment by yzraeu** [comment]
@ladynaggaga any news about the other courses?

**Comment by TechWatching** [comment]
There are available on MVA now ☺️

**Comment by rafaelbarrelo** [comment]
@yzraeu look here: https://github.com/LadyNaggaga/ASP.NETCoreMVA/issues/4
