### ISSUE TITLE
missing links back to MVA

### ISSUE THREAD

**Issue by DickBaker** [LadyNaggaga/ASP.NETCoreMVA#4]
MVA has 3 courses that point here, but the readme,md only points back to MVA ("Watch..") for the first course, and [as I write this] this was updated 3 months ago, long before release of the Intermediate (Day.2) and X-Plat (Day.3).

MariaN should update the Day.2 & Day.3 links to
https://mva.microsoft.com/en-US/training-courses/intermediate-aspnet-core-10-16964
https://mva.microsoft.com/en-US/training-courses/aspnet-core-10-crossplatform-17039

**Comment by LadyNaggaga** [comment]
They needed to be removed  since they current MVAs don't include the csproj bits
